### ISSUE TITLE
Game won't start after latest mod update.

### ISSUE THREAD

**Issue by YuRaNnNzZZ** [Domaman202/AE2UnlimitedCable#4]
https://gist.github.com/YuRaNnNzZZ/13040299bd44d3c2772be194e20f23d9

AE2AO 1.2.4, AE2 8.1.0-alpha.10, Fabric API 0.24.1 build.412 (1.16.3)

Дооптимизировался так, что забыл включить либу в мод.

**Comment by Domaman202** [comment]
Ой бл@ть

**Comment by Domaman202** [comment]
Пасиб что сказал, щас пофиксим
